export const UNIVERSITIES = [
  { id: 1, name: "Université Internationale de Rabat (UIR)" },
  { id: 2, name: "Université Mohammed VI des Sciences de Santé (UM6SS) - Casablanca" },
  { id: 3, name: "Université Internationale Abulcasis des Sciences de Santé (UIASS) - Rabat" },
  { id: 4, name: "Université Euro-méditerranéenne de Fès (UEMF)" },
  { id: 5, name: "Université Mohammed VI Polytechnique (UM6P) - Ben Guérir" },
  { id: 6, name: "Université Privée Marrakech Tensift El Haouz (UPM)" },
  { id: 7, name: "Université Internationale d'Agadir - Universiapolis" },
  { id: 8, name: "Université Internationale de Casablanca (UIC)" },
  { id: 9, name: "École Supérieure d'Architecture de Casablanca (EAC)" },
  { id: 10, name: "École Centrale de Casablanca (ECC)" },
  { id: 11, name: "ESCA École de Management" },
  { id: 12, name: "Université Privée Mundiapolis - Casablanca" },
  { id: 13, name: "Université Privée de Fès (UPF)" },
  { id: 14, name: "Sup de Co - École Supérieure de Commerce - Marrakech" },
  { id: 15, name: "École Supérieure en Ingénierie de l'Information, Télécoms, Management et Génie Civil (ESTEM) - Casablanca" },
  { id: 16, name: "Institut Supérieur du Génie Appliqué Casablanca (IGA)" },
  { id: 17, name: "École Marocaine des Sciences de l'Ingénieur - Casablanca (EMSI-Casablanca)" },
  { id: 18, name: "École Marocaine des Sciences de l'Ingénieur - Rabat (EMSI-Rabat)" },
  { id: 19, name: "École Marocaine des Sciences de l'Ingénieur - Marrakech (EMSI-Marrakech)" },
  { id: 20, name: "Institut Supérieur d'Ingénierie et des Affaires - Rabat (ISGA-Rabat)" },
  { id: 21, name: "Institut Supérieur d'Ingénierie et des Affaires - Fès (ISGA-Fès)" },
  { id: 22, name: "Institut Supérieur d'Ingénierie et des Affaires - Marrakech (ISGA-Marrakech)" },
  { id: 23, name: "École Marocaine d'Ingénierie (EMG-Rabat)" },
  { id: 24, name: "Institut Supérieur de Transport et de la Logistique (ISTL) - Casablanca" },
  { id: 25, name: "Institut des Hautes Études de Management (HEM) - Casablanca" },
  { id: 26, name: "École des Hautes Études Économiques, Commerciales et d'Ingénierie (HEEC) - Marrakech" },
  { id: 27, name: "École Supérieure de Management de Commerce et d'Informatique (SUP'MANAGEMENT) - Fès" },
  { id: 28, name: "International Institute for Higher Education in Morocco (IIHEM) - Rabat" },
  { id: 29, name: "École d'Ingénierie en Génie des Systèmes Industriels de Casablanca (EIGSICA)" },
  { id: 30, name: "École Supérieure de Management, Informatique et Télécommunication (SUPMTI) - Rabat" },
  { id: 31, name: "École des Hautes Études d'Ingénierie (EHEIO) - Oujda" },
  { id: 32, name: "École de Management et d'Administration des Affaires - Agadir" },
  { id: 33, name: "Institut Supérieur d'Ingénierie et des Affaires (ISGA-Casablanca)" },
  { id: 34, name: "Institut Supérieur de Management, d'Administration et de Génie Informatique (ISMAGI)" },
  { id: 35, name: "Écoles des Hautes Études en Sciences et Techniques de l'Ingénierie et du Management Privée (HESTIM)" },
  { id: 36, name: "École des Hautes Études Commerciales et Informatiques - Casablanca (HECI-Casablanca)" },
  { id: 37, name: "École Supérieure des Sciences Économiques et de Management (ESSEM)" },
  { id: 38, name: "École Supérieure de Management et de Gestion des Ressources Humaines (SUP'RH)" },
  { id: 39, name: "École Supérieure des Sciences de Santé (ESSS) - Casablanca" },
  { id: 40, name: "École des Nouvelles Sciences et Ingénierie (ENSIT) - Tanger" },
  { id: 41, name: "Écoles Marocaines des Sciences de l'Ingénieur en Informatique Industrielle et Informatique de Gestion (EMSI-Tanger)" },
  { id: 42, name: "École Privée des Hautes Études Comptables et Financières (HECF) - Fès" },
];
